### ISSUE TITLE
Add info: Deployed on Rinkeby

### ISSUE THREAD

**Issue by dmitry537** [pipermerriam/ethereum-datetime#16]
ethereum-datetime at Rinkeby network:
0x92482Ba45A4D2186DafB486b322C6d0B88410FE7

Virified on etherscan:
[https://rinkeby.etherscan.io/address/0x92482ba45a4d2186dafb486b322c6d0b88410fe7](https://rinkeby.etherscan.io/address/0x92482ba45a4d2186dafb486b322c6d0b88410fe7)

**Comment by pipermerriam** [comment]
Please link to a verified contract on etherscan or something similar.
