### ISSUE TITLE
api function arguments invalid 

### ISSUE THREAD

**Issue by vjuge** [pipermerriam/ethereum-datetime#3]
hello,

in the api.sol file, the arguments of functions are not the same than in DateTime.sol, some arguments are uint17, despite in the solidity contract it's uint8.
This makes truffle build crash.

please fix it with : 
api.sol : 
[..]
        function getMonth(uint timestamp) constant returns (uint8);
        function getDay(uint timestamp) constant returns (uint8);
        function getHour(uint timestamp) constant returns (uint8);
        function getMinute(uint timestamp) constant returns (uint8);
        function getSecond(uint timestamp) constant returns (uint8);
[..]

**Comment by pipermerriam** [comment]
@vjuge would you be willing to open up a pull request making this change?

**Comment by DaveAppleton** [comment]
OK - I did it :-)

**Comment by pipermerriam** [comment]
Closed via #5
