### ISSUE TITLE
Example how to use it 

### ISSUE THREAD

**Issue by bachvtuan** [pipermerriam/ethereum-datetime#6]
Hello, I'm newbie in Solidity,
Can you help you by give example code how to import your code and use it ?

**Comment by dmitry537** [comment]
0x92482Ba45A4D2186DafB486b322C6d0B88410FE7 - ethereum-datetime contract on Rinkeby network, change it for you network.

`pragma solidity ^0.4.21;

contract DateTimeAPI {
        /*
         *  Abstract contract for interfacing with the DateTime contract.
         *
         */
        function isLeapYear(uint16 year) constant returns (bool);
        function getYear(uint timestamp) constant returns (uint16);
        function getMonth(uint timestamp) constant returns (uint8);
        function getDay(uint timestamp) constant returns (uint8);
        function getHour(uint timestamp) constant returns (uint8);
        function getMinute(uint timestamp) constant returns (uint8);
        function getSecond(uint timestamp) constant returns (uint8);
        function getWeekday(uint timestamp) constant returns (uint8);
        function toTimestamp(uint16 year, uint8 month, uint8 day) constant returns (uint timestamp);
        function toTimestamp(uint16 year, uint8 month, uint8 day, uint8 hour) constant returns (uint timestamp);
        function toTimestamp(uint16 year, uint8 month, uint8 day, uint8 hour, uint8 minute) constant returns (uint timestamp);
        function toTimestamp(uint16 year, uint8 month, uint8 day, uint8 hour, uint8 minute, uint8 second) constant returns (uint timestamp);
}


contract Example {        
    
    DateTimeAPI dateTime;
    address dateTimeContractAddress = 0x92482Ba45A4D2186DafB486b322C6d0B88410FE7;
    
    constructor() {
        dateTime = DateTimeAPI(dateTimeContractAddress);
    }
    
    function getYear(uint timestamp) public constant returns (uint16) {
        return dateTime.getYear(timestamp);
    }
}
`

**Comment by bachvtuan** [comment]
Asked over year and now I get support. thanks !
