### ISSUE TITLE
Make this an ethpm package

### ISSUE THREAD

**Issue by thedewpoint** [pipermerriam/ethereum-datetime#7]
I would love to use this but right now I'm hacking everything up to work in development and in the test net. Could you help with this? I'm too new to figure how to do it myself

**Comment by doppio** [comment]
Would also be nice if this could be published on NPM.

**Comment by uluhonolulu** [comment]
I can handle both, if you don't mind.

**Comment by uluhonolulu** [comment]
Published to NPM: https://www.npmjs.com/package/ethereum-datetime

**Comment by pipermerriam** [comment]
Thank @uluhonolulu

**Comment by amitaymolko** [comment]
Was this published to ethpm?

**Comment by uluhonolulu** [comment]
No, I was getting strange compilation errors, realized that I'd have to upgrade it to the latest Solidity, and had no time for it.
