### ISSUE TITLE
Trouble With Inheritance and Calling toTimestamp Method

### ISSUE THREAD

**Issue by Samyoul** [pipermerriam/ethereum-datetime#9]
I'm not sure if this is an issue with the contract, and issue with my coding or an issue with solidity or the IDE I'm using (Remix), but I have an issue nonetheless. I've asked them as question on the Ethereum stackoverflow for two different approaches with two different compile errors on the same line:

- [TypeError: Member “toTimestamp” is not available in contract DateTime outside of storage](https://ethereum.stackexchange.com/questions/27523/typeerror-member-totimestamp-is-not-available-in-contract-datetime-outside-of)
- [No matching declaration found after argument-dependent lookup](https://ethereum.stackexchange.com/questions/27662/no-matching-declaration-found-after-argument-dependent-lookup)

A sample of the code I'm working on can be found here : https://ethereum.github.io/browser-solidity/#version=soljson-v0.4.17+commit.bdeb9e52.js&gist=03e5543f137d3ec464462cc190104de3

Why is the compiler giving these errors?

**Comment by pipermerriam** [comment]
The problem is that your `newMonth` variable is a `uint16` when it needs to be a `uint8` based on the function signature of `toTimestamp`.

```javascript
uint time = toTimestamp(
            year,
            uint8(newMonth),   // <--- if you cast to uint8 the error goes away
            getDay(_timestamp),
            getHour(_timestamp),
            getMinute(_timestamp),
            getSecond(_timestamp)
        );
```

**Comment by Samyoul** [comment]
Ugh, I am an idiot!

**Comment by pipermerriam** [comment]
Don't worry.  I'm an idiot too.
